
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn, AbstractEntity } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'







interface RootletStaticFieldsConstructorInput {
  id: ID;
  attributes: String;
  description: String;
  imageUrl: String;
  number: BigInt;
  someAddress: String;
}
@Entity("RootletStaticFields")
export class RootletStaticFields extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("String")
	attributes: String

	@Required
	@Column("String")
	description: String

	@Required
	@Column("String")
	imageUrl: String

	@Required
	@Column("BigInt")
	number: BigInt

	@Required
	@Column("String")
	someAddress: String
  constructor(data: RootletStaticFieldsConstructorInput) {super()}
  
}


const source = `type RootletStaticFields @entity {
  id: ID!
  attributes: String!
  description: String!
  imageUrl: String!
  number: BigInt!
  someAddress: String!
} `
DatabaseSchema.register({
  source,
  entities: {
    "RootletStaticFields": RootletStaticFields
  }
})
